# Generated by Django 5.2.8 on 2026-05-15 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experiments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="称呼/姓名"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=120, verbose_name="地区"),
                ),
                (
                    "age_range",
                    models.CharField(blank=True, max_length=50, verbose_name="年龄段"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=50, verbose_name="性别"),
                ),
                (
                    "organization_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="学校/单位类型"
                    ),
                ),
                (
                    "education_or_work",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="教育阶段/职业状态"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="联系方式"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="experiments.experimentbatch",
                        verbose_name="实验批次",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "参与者资料",
                "verbose_name_plural": "参与者资料",
            },
        ),
    ]
