# Generated by Django 5.2.14 on 2026-05-23 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('experiments', '0016_step_title_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='experiments.experimentbatch', verbose_name='实验批次'),
        ),
    ]
