# Generated by Django 5.2.8 on 2026-05-15 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experiments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="zh-hans", max_length=12, verbose_name="界面语言"
                    ),
                ),
                (
                    "topic_order_snapshot",
                    models.JSONField(default=list, verbose_name="话题初始随机快照"),
                ),
                (
                    "submitted_topic_order",
                    models.JSONField(
                        blank=True, default=list, verbose_name="参与者排序"
                    ),
                ),
                (
                    "selected_high_topic_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="最高话题 ID"
                    ),
                ),
                (
                    "selected_low_topic_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="最低话题 ID"
                    ),
                ),
                (
                    "round_order",
                    models.JSONField(blank=True, default=list, verbose_name="轮次顺序"),
                ),
                (
                    "current_session_step",
                    models.CharField(
                        default="topic_order",
                        max_length=30,
                        verbose_name="当前会话步骤",
                    ),
                ),
                (
                    "current_round_index",
                    models.PositiveIntegerField(default=0, verbose_name="当前轮次序号"),
                ),
                (
                    "batch_snapshot",
                    models.JSONField(default=dict, verbose_name="批次快照"),
                ),
                (
                    "step_started_at",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="步骤开始时间"
                    ),
                ),
                (
                    "step_submitted_at",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="步骤提交时间"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="experiments.experimentbatch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_session",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "答题会话",
                "verbose_name_plural": "答题会话",
            },
        ),
        migrations.CreateModel(
            name="QualityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=40, verbose_name="事件类型"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_events",
                        to="survey.surveysession",
                    ),
                ),
            ],
            options={
                "verbose_name": "质量事件",
                "verbose_name_plural": "质量事件",
            },
        ),
        migrations.CreateModel(
            name="TopicRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_type",
                    models.CharField(
                        choices=[("high", "最高话题"), ("low", "最低话题")],
                        max_length=10,
                        verbose_name="轮次类型",
                    ),
                ),
                ("topic_id", models.PositiveIntegerField(verbose_name="话题 ID")),
                (
                    "material_snapshot",
                    models.JSONField(default=dict, verbose_name="材料快照"),
                ),
                (
                    "current_step",
                    models.CharField(
                        default="post", max_length=40, verbose_name="当前轮次步骤"
                    ),
                ),
                (
                    "step_started_at",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="步骤开始时间"
                    ),
                ),
                (
                    "step_submitted_at",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="步骤提交时间"
                    ),
                ),
                (
                    "skipped_ai",
                    models.BooleanField(default=False, verbose_name="跳过 AI"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="已完成"),
                ),
                (
                    "ai_mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="experiments.aimode",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="survey.surveysession",
                    ),
                ),
            ],
            options={
                "verbose_name": "话题轮次",
                "verbose_name_plural": "话题轮次",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TextResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=40, verbose_name="步骤")),
                ("final_text", models.TextField(verbose_name="最终文本")),
                (
                    "input_method",
                    models.CharField(
                        default="keyboard", max_length=40, verbose_name="输入方式"
                    ),
                ),
                (
                    "transcribe_model",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="转写模型"
                    ),
                ),
                (
                    "was_edited",
                    models.BooleanField(default=False, verbose_name="是否编辑过"),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(default=0, verbose_name="字数"),
                ),
                (
                    "elapsed_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="用时秒数"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_responses",
                        to="survey.topicround",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScaleResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=40, verbose_name="步骤")),
                ("item_type", models.CharField(max_length=40, verbose_name="量表类型")),
                (
                    "item_label",
                    models.CharField(max_length=240, verbose_name="题目文本"),
                ),
                ("language", models.CharField(max_length=12, verbose_name="语言")),
                ("min_value", models.IntegerField(default=1, verbose_name="最小值")),
                ("max_value", models.IntegerField(default=7, verbose_name="最大值")),
                ("selected_value", models.IntegerField(verbose_name="选中值")),
                (
                    "elapsed_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="用时秒数"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scale_responses",
                        to="survey.topicround",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("participant", "参与者"),
                            ("assistant", "AI"),
                            ("system", "系统"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("language", models.CharField(max_length=12, verbose_name="语言")),
                (
                    "ai_mode_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="AI 模式"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="模型名称"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_messages",
                        to="survey.topicround",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_snapshot_id",
                    models.PositiveIntegerField(verbose_name="评论快照 ID"),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[("like", "赞"), ("dislike", "踩"), ("none", "无操作")],
                        default="none",
                        max_length=20,
                        verbose_name="反应",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reactions",
                        to="survey.topicround",
                    ),
                ),
            ],
        ),
    ]
