# Generated by Django 5.2.8 on 2026-05-16 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_postreaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnglishPaperResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="论文要求")),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="时长（小时）"
                    ),
                ),
                ("paper_text", models.TextField(verbose_name="英文论文")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="english_paper_response",
                        to="survey.surveysession",
                    ),
                ),
            ],
        ),
    ]
