# Generated by Codex on 2026-05-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_englishpaperresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnglishPaperDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt", models.TextField(blank=True, verbose_name="论文要求")),
                ("duration_hours", models.PositiveIntegerField(default=24, verbose_name="时长（小时）")),
                ("paper_text", models.TextField(blank=True, verbose_name="英文论文草稿")),
                ("saved_at", models.DateTimeField(auto_now=True, verbose_name="暂存时间")),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="english_paper_draft",
                        to="survey.surveysession",
                    ),
                ),
            ],
        ),
    ]
