# Generated by Django 5.2.14 on 2026-05-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_englishpaperdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='interrupted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='中断时间'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='was_interrupted',
            field=models.BooleanField(default=False, verbose_name='被用户中断'),
        ),
    ]
