# Generated by Django 5.2.14 on 2026-05-23 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0016_step_title_fields'),
        ('survey', '0005_conversationmessage_interrupted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysession',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='experiments.experimentbatch'),
        ),
    ]
